repos:

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.7
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format

- repo: https://github.com/python-poetry/poetry
  rev: '2.1.1'
  hooks:
    - id: poetry-check
    - id: poetry-lock